### ISSUE TITLE
Module throws an error in v10 at activation

### ISSUE THREAD

**Issue by dlemckert** [League-of-Foundry-Developers/simplefog#81]
Simplefog | Performing migration #1
2commons.js:1250 Error: You are accessing the Scene#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1239:19)
    at Scene._logV10CompatibilityWarning (commons.js:6143:14)
    at get data [as data] (commons.js:6043:24)
    at SimplefogMigrations.js:25:13
    at Scenes.forEach (commons.js:2802:9)
    at SimplefogMigrations.migration1 (SimplefogMigrations.js:23:17)
    at SimplefogMigrations.check (SimplefogMigrations.js:12:38)
    at Object.fn (simplefog.js:47:23)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
logCompatibilityWarning @ commons.js:1250
_logV10CompatibilityWarning @ commons.js:6143
get data @ commons.js:6043
(anonymous) @ SimplefogMigrations.js:25
forEach @ commons.js:2802
migration1 @ SimplefogMigrations.js:23
check @ SimplefogMigrations.js:12
(anonymous) @ simplefog.js:47
#call @ foundry.js:688
callAll @ foundry.js:645
setupGame @ foundry.js:7769
await in setupGame (async)
_initializeGameView @ foundry.js:8820
_initializeView @ foundry.js:8796
initialize @ foundry.js:7630
await in initialize (async)
window.addEventListener.once @ foundry.js:78537
foundry.js:691 Foundry VTT | Error thrown in hooked function '' for hook 'ready'
#call @ foundry.js:691
callAll @ foundry.js:645
setupGame @ foundry.js:7769
await in setupGame (async)
_initializeGameView @ foundry.js:8820
_initializeView @ foundry.js:8796
initialize @ foundry.js:7630
await in initialize (async)
window.addEventListener.once @ foundry.js:78537
foundry.js:711 TypeError: Error thrown in hooked function '' for hook 'ready'. Cannot read properties of undefined (reading 'refresh')
    at Object.fn (simplefog.js:50:16)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Game.setupGame (foundry.js:7769:11)
    at async Game._initializeGameView (foundry.js:8820:5)
    at async Game.initialize (foundry.js:7630:5)

**Comment by UranusBytes** [comment]
Support for v10 is actively underway.  No ETA at this time.

https://github.com/League-of-Foundry-Developers/simplefog/issues/78
